meta_product_name: "トランスロード"
meta_title: "トランスロード・送りたい品物にマッチする運送会社を無料で、すぐに、簡単に、見つけられる"
meta_description: "トランスロードは、荷主企業が送りたい品物にマッチする運送会社をご紹介するサービスです。運送会社の登録料、使用料はありません。登録が完了したらすぐに、マッチする荷主企業にご紹介できる流れになっております。"
meta_image: "cover.png"  # should exist in `app/assets/images/`